- include: postfix.yml tags=postfix
- include: dovecot.yml tags=dovecot
- include: opendkim.yml tags=opendkim
- include: opendmarc.yml tags=opendmarc
- include: rspamd.yml tags=rspamd
- include: solr.yml tags=solr
- include: checkrbl.yml tags=checkrbl
- include: z-push.yml tags=zpush
- include: autoconfig.yml tags=autoconfig

